### PR TITLE
added CSS image background example

### PR DESCRIPTION
**Pull request by jonchambers**
Added CSS image background example

### CODE REVIEW

**Comment by nbriz** [comment]
hey @jonchambers this is great! love that u broke it down using the individual `background-*` properties instead of using the [`background` shortcut](https://css-tricks.com/perfect-full-page-background-image/) (much clearer for beginners to understand this way). got  a couple edits/suggestions for u:

## 1. indentation

could we indent a little cleaner? instead of this:
```html
<style>
  html { 
  background: url(https://raw.githubusercontent.com/jonchambers/twineImages/master/nebula.jpg);
  background-size: cover;
  background-attachment: fixed;
  background-position: center;  
  background-repeat: no-repeat;
}
</style>
```
could we do this
```html
<style>

  html { 
    background: url(https://raw.githubusercontent.com/jonchambers/twineImages/master/nebula.jpg);
    background-size: cover;
    background-attachment: fixed;
    background-position: center;  
    background-repeat: no-repeat;
  }

</style>
```

## 2. Background Property

Instead of using the `background` property for this one, let's make it explicit like the rest && use `background-image`. Then instead of using an absolute path to an external resource, could u upload that image to the repo so we can just write `url(images/bg/nebula.jpg)`. We've got images we've been using for demos like these in `www/images`, maybe create a new folder in there called "bg" && place it in there (assuming that's a royalty free image).

Then in the speech bubble, could we wrap "url()" in code tags `<code>url()</code>` + also call it a CSS function, something like: 
> "the CSS <code>url()</code> function's value should be a path to an image that should be set as our background"

**Comment by jonchambers** [comment]
Sounds good! I'll fix this up soon :)

**Comment by jonchambers** [comment]
@nbriz just added and updated the css background image example branch

**Comment by nbriz** [comment]
@jonchambers the indentation still seems off on my end? if u ask netnet to "tidy" your code it should clean that up and make the CSS class's bracket's line up with each other

**Comment by jonchambers** [comment]
@nbriz sorry about that, should be good now

**Comment by nbriz** [comment]
perfect! thnx @jonchambers merging now!

**Pull request merged**
