### PR TITLE
Issue #212: Create Convo File for this Widget

### PR DESCRIPTION
**Pull request by Cthomp7**
I have the functionality of the Demo/Example Maker widget loading! Let me know if there are any issues. I haven't looked at this in a hot minute, so there might be something buggy I am missing.

How do I close the welcome layouts convo? I tried `window.convo.hide()` on line 210 in www/widgets/DemoExampleMaker.js

_For myself:_
- [ ] remove extra `calledBy` variable in `_uploadJSON()`

### CODE REVIEW

**Comment by nbriz** [comment]
@Cthomp7 so excited to see this come through!
we (have almost) refactored the entire code base recently (nearly there) so this might need some addressing in order to merge properly. i'm thinking the easiest thing would be to add my fork as a new remote:
```
git remote add nick https://github.com/nbriz/netnet.studio.git
```
&& then pull from the[ refactored branch](https://github.com/nbriz/netnet.studio/tree/refactor-v3) @sarahrooney && i have been working on
```
git pull nick refactor-v3
```
u'll likely have some conflicts u'll need to resolve, but if that gets too messy send me an email && we can schedule a time to zoom && resolve it together :)

**Comment by Cthomp7** [comment]
Sounds good, I will definitely do that! I will let you know if there are any issues with the refactor branch or if I have any questions :)

**Comment by nbriz** [comment]
@Cthomp7 seems like it couldn't merge b/c of conflicts. this might be a trickier/messier merge than usual, might be easiest to do this together over zoom maybe? would u be up for that? there are faculty-folks that could really benefit from these updates this semester so would be great to get this into the next update! send me an email to schedule a call when u've got time :)

**Comment by nbriz** [comment]
i'm gonna close this PR seeing as how we worked this into the refactor :)

**Pull request closed without merging**
