### PR TITLE
Issue #237: close generated link

### PR DESCRIPTION
**Pull request by Cthomp7**
Added `this.$('[name="dem-url"]').style.display = 'none'` to the end of the DEM `_updateStep`. This hides/closes the old generated link every time the example is updated or a new example is loaded in. #237

### CODE REVIEW

**Comment by nbriz** [comment]
@Cthomp7 this is ready to go as is, but what do u think about also adding that line at the bottom of the `_addStep` method? that way it closes as soon as the user adds a new line (even if technically the new step hasn't been saved yet).

**Comment by nbriz** [comment]
@Cthomp7 thoughts on my comment above?

**Comment by Cthomp7** [comment]
@nbriz I don't think that's a bad idea. We can always remove later if need be. Let me add that quick.

**Comment by Cthomp7** [comment]
@nbriz Just pushed and cleaned up the merge since there was a conflict. Conflict was just from newer reorderable list stuff in the `_addStep` method. Should be good to go!

**Comment by nbriz** [comment]
@Cthomp7 i pulled changes && now i'm getting an error soon as i open the widget (which seems to block most of the rest of the functionality from working, can't add steps or generate links, etc)

in Firefox:
```
TypeError: step is undefined
    _selectStep http://localhost:8001/widgets/demo-example-maker/index.js:300
```

in Chrome:

```
TypeError: Cannot read properties of undefined (reading 'title')
    at DemoExampleMaker._selectStep (index.js:299:49)
 ```

**Comment by Cthomp7** [comment]
@nbriz I was looking into the issue you mentioned above and I was not able to recreate this. Would you be able to pull the newest version of this branch and let me know if you are still receiving this error? I merged the newest version of the DEM with the reorderable list to see if this issue appeared with the newest code and still no issues. 

If you do still receive the error if you can explain what actions you took to create this error that would be greatly appreciated!😺

**Pull request merged**
